### ISSUE TITLE
heap corruption

### ISSUE THREAD

**Issue by playmiel** [wollewald/EEPROM_SPI_WE#1]
when I test the write-read demo after the setup I have a heap corruption (I have an esp32 wrover)

**Comment by wollewald** [comment]
Hi @playmiel ,

you tested the sketch EEPROM_SPI_WE_basic_read_write.ino, correct? 

Did you change lines 69 to 74 as written in the sketch? 

Original:
````
  String stringToWrite = "This is no poetry, I am just a simple test String";
  String stringToRead = "";
  /* For ESP32 and ESP8266 based boards String read/write does not work
     this way. Use char arrays instead: */
  // char stringToWrite[] = "This is no poetry, I am just a simple test String"; 
  // char stringToRead[100] = ""; 
````
You need to change to:
````
  // String stringToWrite = "This is no poetry, I am just a simple test String";
  // String stringToRead = "";
  /* For ESP32 and ESP8266 based boards String read/write does not work
     this way. Use char arrays instead: */
  char stringToWrite[] = "This is no poetry, I am just a simple test String"; 
  char stringToRead[100] = ""; 
````
Without the change I also get the heap corruption error, that's why I wrote this instruction. With the change it works at least on a ESP32 Development Board (ESP-WROOM-32).

**Comment by playmiel** [comment]
oh I didn't notice the line code in commentary
thanks I'll test this tomorrow and I'll let you know if it works well

**Comment by playmiel** [comment]
hi this works well thanks
